import { getRandomData } from '../../../utils/getRandomData';

export const statisticsByDays = [
  {
    color: '#4CAF50',
    data: getRandomData(14),
    description: 'Детское питание, готовая еда, овощи',
    id: 1,
    title: 'Продукты',
  },
  {
    color: '#F2F2F2',
    data: getRandomData(14),
    description: 'Аптеки, врачи',
    id: 7,
    title: 'Здоровье',
  },
  {
    color: '#1F1F1F',
    data: getRandomData(14),
    description: 'Страховка, ТО, бензин, штрафы',
    id: 10,
    title: 'Машина',
  },
  {
    color: '#E51400',
    data: getRandomData(14),
    description: 'КФС, Старбакс, Макдоналдс',
    id: 31,
    title: 'Кафе',
  },
  {
    color: '#673AB7',
    data: getRandomData(14),
    description: 'Платные подписки, программы',
    id: 28,
    title: 'Инфопродукты',
  },
  {
    color: '#795548',
    data: getRandomData(14),
    description: 'Косметика, салоны, шампуни, зубная паста',
    id: 8,
    title: 'Уход за собой',
  },
  {
    color: '#9E9E9E',
    data: getRandomData(14),
    description: 'Родители, подарки, цветы',
    id: 21,
    title: 'Прочие расходы',
  },
  {
    color: '#607D8B',
    data: getRandomData(14),
    description: 'Мобильная связь, коммуналка, штрафы',
    id: 9,
    title: 'Обязательные платежи',
  },
  {
    color: '#3F51B5',
    data: getRandomData(14),
    description: 'Книги, курсы',
    id: 14,
    title: 'Саморазвитие',
  },
  {
    color: '#FFEB3B',
    data: getRandomData(14),
    description: 'Тройка, такси',
    id: 4,
    title: 'Транспорт',
  },
  {
    color: '#E91E63',
    data: getRandomData(14),
    description: 'Детские зоны, кино, зоопарк',
    id: 12,
    title: 'Развлечения',
  },
  {
    color: '#F472D0',
    data: getRandomData(14),
    description: 'Игрушки, детская одежда',
    id: 2,
    title: 'Дети',
  },
  {
    color: '#2196F3',
    data: getRandomData(14),
    description: 'Компьютеры, телефоны, аксессуары',
    id: 30,
    title: 'Техника',
  },
  {
    color: '#A0522D',
    data: getRandomData(14),
    description: 'Моющие средства, ремонт, мебель',
    id: 5,
    title: 'Дом',
  },
  {
    color: '#FF9800',
    data: getRandomData(14),
    description: 'Доставка, уборка',
    id: 32,
    title: 'Услуги',
  },
  {
    color: '#6D8764',
    data: getRandomData(14),
    description: 'Одежда и обувь (не детская)',
    id: 3,
    title: 'Одежда',
  },
];
